# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5649390b550dec97e712b2ae71e14cfb60fee79dfe64eac080702599461ee5f7acab41adb2d2fa1ead4244bc5e2d46fec9dd6e90ac60c2076d80b4a0c4f9830

test:
  secret_key_base: ceaa7d95c5466b6781c8a9d4f2774782fb5df505a865dba5a3e791ef42de1bd47345a74d266d92a875d4bbcd41acac327feb0c32ac3cba44032c651562806f80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
